cockroach/urls.py
from django.urls import path, include
from . import views
import django_eventstream

app_name = 'cockroach'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:tag>/', views.game, name='game'),
]

games/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('skull/', include('skull.urls')),
    path('nothanks/', include('nothanks.urls')),
    path('cockroach/', include('cockroach.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

cockroach/models.py
import uuid
from django.db import models

class Game(models.Model):
    # games are identified by a user-specified tag, as with Codenames
    tag = models.CharField(max_length=32, primary_key=True)
    
    # probably don't care about these, but...
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    # the most recent game state notification message
    status = models.CharField(max_length=200, default='')
        
    # game phase
    class Stage(models.IntegerChoices):
        # waiting for players to join
        GATHERING = 0
        
        # lead player must choose a card
        STARTING = 1
        
        # next player must view, pass or call
        PLAYING = 2
        
        # game is finished
        GAME_OVER = 3

    stage = models.IntegerField(choices=Stage.choices, default=Stage.GATHERING)
    next_player = models.IntegerField(default=-1)
    
    # the card being passed around this round
    card = models.IntegerField(default=-1)
    
    # can a player win by getting all suits?
    house_rules = models.BooleanField(default=False)
    
    @classmethod
    def create(cls, tag, owner_nickname, house_rules):
        game = cls(tag=tag, house_rules=house_rules)
        game.save()
        game.player_set.create(game=game, nickname=owner_nickname, owner=True)
        return game
    
    def round_start (self, next_player=0):
        self.stage = Game.Stage.STARTING
        self.next_player = next_player
        self.card = -1
        self.save()
    
    def end_game (self):
        self.stage = Game.Stage.GAME_OVER
        self.next_player = -1
        self.card = -1
        self.save()
        
    def __str__(self):
        return self.tag
    

class Player(models.Model):
    # each player has a unique token which is passed when moving
    # in order to validate their move
    token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # players exist only within context of a game
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    
    # players supply their own nickname when joining a game
    nickname = models.CharField(max_length=32)
    
    # using strings for this kinda sucks, but it's easier than trying
    # to do proper data structures in DB tables, and the structs are very simple
    
    # hidden cards from which player may choose
    hand = models.CharField(max_length = 100, default='')
    
    # face up cards player has had to take
    tricks = models.CharField(max_length = 100, default='')
    
    # allocated on game start
    # -- in this game there isn't a fixed turn order, but we'll keep a
    # a random ordering for display purposes
    turn_order = models.IntegerField(default=-1)
    
    # first player to join a game gets to start it
    owner = models.BooleanField(default=False)
    
    # has this player seen the current card?
    seen = models.BooleanField(default=False)
    
    # what has this player claimed the card to be?
    claim = models.IntegerField(default=-1)
    
    # who has this player passed to?
    target = models.IntegerField(default=-1)
    
    # who did this player receive from?
    nominator = models.IntegerField(default=-1)

    # player status
    class Status(models.IntegerChoices):
        # waiting for players to arrive
        WAITING = 0
        
        # passing cards
        PLAYING = 1
        
        # waiting for players to play
        WATCHING = 2
        
        # player has lost
        LOST = 3
        
        # player has won
        WON = 4
    
    status = models.IntegerField(choices=Status.choices, default=Status.WAITING)
    
    
    def __str__(self):
        return self.nickname
    
    def reset (self, turn_order=-1, hand=''):
        self.turn_order = turn_order
        self.hand = hand
        self.tricks = ''
        self.save()
    
    def round_start (self, next_player=0):
        self.claim = -1
        self.seen = False
        self.target = -1
        if self.turn_order == next_player:
            self.nominator = self.turn_order
            self.status = Player.Status.PLAYING
        else:
            self.nominator = -1
            self.status = Player.Status.WATCHING
            
        self.save()
    
    
        
    
    
    

cockroach/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from django_eventstream import send_event

from .models import Game
from . import game_logic as GM

import json

# send messages to game clients to notify of state changes
# no idea how this is going to work yet,
# for now it's a placeholder
def send_notification (request, tag, msg, action='refresh'):
    try:
        game = Game.objects.get(pk=tag)
        game.status = msg
        game.save()
        
    except Game.DoesNotExist:
        pass

    # send message irrespective of game existence, to notify destruction
    send_event(tag, 'message', {'text':action})

def as_int(x, subst):
    try:
        return int(x)
    except Exception:
        return subst

# index page: join a game
def index(request):
    return render(request, 'cockroach/index.html', {})

# game page: view game state, optionally performing an action
def game(request, tag):
    action = request.POST.get('move', None)
    token = request.session.get('cock_token', request.POST.get('token', 'nobody'))
    how = request.POST.get('how', None)
    notify = False
    
    if action=='join':
        nick = request.POST.get('nick', None)
        if nick is None:
            return render(request, 'cockroach/index.html', { 'msg' : 'you must provide a valid nickname to join a game' })
        house_rules = request.POST.get('house_rules', 'no') == 'yes'
        
        token, msg, notify = GM.join(tag, nick, house_rules=house_rules)
        if token is not None:
            request.session['cock_token'] = token
        
    elif action=='start':
        msg, notify = GM.start(tag, token)


    elif action=='play':
        card_idx = as_int(request.POST.get('card_idx', '-1'), -1)
        target = as_int(request.POST.get('target', '-2'), -2)
        claim = as_int(request.POST.get('claim', '-1'), -1)
        
        msg, notify = GM.play(tag, token, card_idx=card_idx, target=target, claim=claim)


    elif action=='peek':
        msg, notify = GM.peek(tag, token)

    elif action=='refer':
        target = as_int(request.POST.get('target', '-2'), -2)
        claim = as_int(request.POST.get('claim', '-1'), -1)
        
        msg, notify = GM.refer(tag, token, target=target, claim=claim)
    
    elif action=='call':
        verdict = request.POST.get('verdict', 'no') == 'yes'
        
        msg, notify = GM.call(tag, token, verdict)
        
    elif action=='destroy':
        success, msg = GM.destroy(tag, token)
        if success:
            send_notification(request, tag, msg, action='index')
            return render(request, 'cockroach/index.html', { 'msg' : msg })
    else:
        msg = 'You are viewing this game as non-player.' if token=='nobody' else ''
        notify = False
    
    if notify:
        send_notification(request, tag, msg)
        msg = ''
    
    msg = msg or ''

    state = GM.visible_state(tag, token)
    state['msg'] = msg
    
    if how == 'json':
        return JsonResponse(state)
    else:
        state['json_state'] = json.dumps(state)
        return render(request, 'cockroach/game.html', state)

cockroach/templates/cockroach/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8"/>
    <link href="{% static 'join.css' %}" rel="stylesheet" type="text/css">
    <title>Cockroach Poker</title>
</head>
<body>
<div class="container">
<h1>COCKROACH POKER</h1>
    
{% if msg %}
<div class="msg">{{ msg }}</div>
{% endif %}

<div class="join-box">
<h2>Join a game</h2>
<form action="{% url 'cockroach:index' %}" method="post" id="join-form">
{% csrf_token %}
    <div class="join-chunk">
        <label>Game Name</label><br>
        <input id="game-name" type="text" size="16" required pattern="[A-Za-z0-9_]+" class="join-field" autofocus/>
    </div>
    
    <div class="join-chunk">
        <label>Player Name</label><br>
        <input id="nick" type="text" size="16" required pattern="[A-Za-z0-9_]+" name="nick" class="join-field"/>
    </div><!-- join-chunk -->

    <div class="join-chunk note">Allowed characters: letters, numbers, underscores</div>
    
    <div class="join-chunk">
        <input type="checkbox" name="house_rules" value="yes" checked />
        <label for="house_rules">House Rules</label>
    </div><!-- join-chunk -->

    <div class="join-chunk note">
        House rules: if a player gets at least one
        (but less than four) of every suit, they win.
    </div>
    

    <div class="control" id="join">Join</div>
    <input type="hidden" name="move" value="join">
</form>
</div><!-- join-box -->

<script>
    document.querySelector('#nick').onkeyup = function(e)
    {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#join').click();
        }
    };

    document.querySelector('#join').onclick = function(e)
    {
        var gameName = document.querySelector('#game-name').value;
        document.querySelector('#join-form').action = '/cockroach/' + gameName + '/';
        if ( document.querySelector('#join-form').reportValidity() )
        {
            document.querySelector('#join-form').submit();
        }
    };
</script>
</div><!-- container -->
</body>
</html>