games/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('skull/', include('skull.urls')),
    path('nothanks/', include('nothanks.urls')),
    path('cockroach/', include('cockroach.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

nothanks/urls.py
from django.urls import path, include
from . import views
import django_eventstream

app_name = 'nothanks'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:tag>/', views.game, name='game'),
]

nothanks/models.py
import uuid
from django.db import models

# this conceptually belongs in game_logic but is too tiresome to put there
INITIAL_CASH = 11

class Game(models.Model):
    # games are identified by a user-specified tag, as with Codenames
    tag = models.CharField(max_length=32, primary_key=True)
    
    # probably don't care about these, but...
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    # the most recent game state notification message
    status = models.CharField(max_length=200, default='')
    
    # whether we're playing with the proper rules or the incorrect ones
    house_rules = models.BooleanField(default=False)
    
    # how many rounds to play
    num_rounds = models.IntegerField(default=3)
    
    # current round
    round = models.IntegerField(default=0)
    
    # game phase
    class Stage(models.IntegerChoices):
        # waiting for players
        GATHERING = 0
        
        # waiting for everyone to place first
        PLAYING = 1
        
        # players have option of bidding or passing
        ROUND_OVER = 2
        
        # game complete
        GAME_OVER = 3

    stage = models.IntegerField(choices=Stage.choices, default=Stage.GATHERING)
    next_player = models.IntegerField(default=-1)
    
    # once again, using strings for this is crappy
    # but going full relational seems like overkill
    deck = models.CharField(max_length = 100, default='')
    pool = models.IntegerField(default=0)
    
    @classmethod
    def create(cls, tag, owner_nickname, num_rounds=3, house_rules=False):
        game = cls(tag=tag, num_rounds=num_rounds, house_rules=house_rules)
        game.save()
        game.player_set.create(game=game, nickname=owner_nickname, owner=True)
        return game
    
    def round_start (self, deck, next_player=0):
        self.stage = Game.Stage.PLAYING            
        self.next_player = next_player            
        self.pool = 0
        self.deck = deck
        self.save()
       
    def advance_player (self):
        current = self.next_player
        players = self.player_set.order_by('turn_order')
        self.next_player = (current + 1) % len(players)
        self.save()
        
    def __str__(self):
        return self.tag
    

class Player(models.Model):
    # each player has a unique token which is passed when moving
    # in order to validate their move
    token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # players exist only within context of a game
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    
    # players supply their own nickname when joining a game
    nickname = models.CharField(max_length=32)
    
    points = models.IntegerField(default=0)
    cash = models.IntegerField(default=INITIAL_CASH)
    
    # using strings for this kinda sucks, but it's easier than trying
    # to do proper data structures in DB tables, and the structs are very simple
    hand = models.CharField(max_length = 100, default='')
    
    # allocated on game start
    turn_order = models.IntegerField(default=-1)
    
    # first player to join a game gets to start it
    owner = models.BooleanField(default=False)
    
    def __str__(self):
        return self.nickname
    
    def reset (self, turn_order=-1):
        self.points = 0
        self.hand = ''
        self.cash = INITIAL_CASH
        self.turn_order = turn_order
        self.save()
    
    def round_start (self):
        self.hand = ''
        self.cash = INITIAL_CASH
        self.save()
    
    
        
    
    
    

nothanks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from django_eventstream import send_event

from .models import Game
from . import game_logic as GM

import json

# send messages to game clients to notify of state changes
# no idea how this is going to work yet,
# for now it's a placeholder
def send_notification (request, tag, msg, action='refresh'):
    try:
        game = Game.objects.get(pk=tag)
        game.status = msg
        game.save()
        
    except Game.DoesNotExist:
        pass

    # send message irrespective of game existence, to notify destruction
    send_event(tag, 'message', {'text':action})

# index page: join a game
def index(request):
    return render(request, 'nothanks/index.html', {})

# game page: view game state, optionally performing an action
def game(request, tag):
    action = request.POST.get('move', None)
    token = request.session.get('nt_token', request.POST.get('token', 'nobody'))
    how = request.POST.get('how', None)
    notify = False
    
    if action=='join':
        nick = request.POST.get('nick', None)
        if nick is None:
            return render(request, 'nothanks/index.html', { 'msg' : 'you must provide a valid nickname to join a game' })
        house_rules = request.POST.get('house_rules', 'no') == 'yes'
        num_rounds = request.POST.get('num_rounds', 3)
        
        try:
            num_rounds = int(num_rounds)
        except Exception:
            num_rounds = 3
        
        token, msg, notify = GM.join(tag, nick, house_rules=house_rules, num_rounds=num_rounds)
        if token is not None:
            request.session['nt_token'] = token
        
    elif action=='start':
        msg, notify = GM.start(tag, token)
    elif action=='take':
        try:
            current_card = int(request.POST.get('card', '-1'))
        except Exception:
            current_card = None
        
        msg, notify = GM.take(tag, token, current_card=current_card)
    elif action=='pay':
        try:
            wallet = int(request.POST.get('wallet', '-1'))
        except Exception:
            wallet = None
        
        msg, notify = GM.pay(tag, token, wallet=wallet)
        
    elif action=='end_round': 
        msg, notify = GM.end_round(tag, token)
    elif action=='destroy':
        success, msg = GM.destroy(tag, token)
        if success:
            send_notification(request, tag, msg, action='index')
            return render(request, 'nothanks/index.html', { 'msg' : msg })
    else:
        msg = 'You are viewing this game as non-player.' if token=='nobody' else ''
        notify = False
    
    if notify:
        send_notification(request, tag, msg)
        msg = ''
    
    msg = msg or ''

    state = GM.visible_state(tag, token)
    state['msg'] = msg
    
    if how == 'json':
        return JsonResponse(state)
    else:
        state['json_state'] = json.dumps(state)
        return render(request, 'nothanks/game.html', state)

nothanks/templates/nothanks/game.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'django_eventstream/eventsource.min.js' %}"></script>
    <script src="{% static 'django_eventstream/reconnecting-eventsource.js' %}"></script>
    <link href="{% static 'nothanks.css' %}" rel="stylesheet" type="text/css">
    <title>No Thanks: {{ tag }}</title>
</head>
<body>
<div id="main" class="main">
    <div id="container" class="container">
        <h1>No Thanks</h1>
        <h2>» {{ tag }} «</h2>
        
        <div class="players" id="players">
            {% for player in players %}
            <div class="player" id="player-{{ forloop.counter0 }}">
                <div class="nickname">{{ player.nickname }}</div>
                <div class="status">{{ player.status }}</div>
                <div class="points">{{ player.points }}</div>
                <div class="hand">
                    {% for cc in player.hand %}
                    <div class="card">{{ cc }}</div>
                    {% endfor %}
                </div><!-- hand -->
            </div><!-- player -->
            {% endfor %}
        </div><!-- players -->

        <div class='game-status' id="game-status">{{ status }}</div>
        
        <div class="tableau" id="tableau">
            <div class="deck">
                <div class="card" id="current_card">{{ card }}</div>
                <div class="decksize" id="decksize">{{ deck_size }}</div>
            </div><!-- deck -->
            <div class="pool-column">
                <div class="pool">
                    <div class="pile" id="pile">
                        <!-- let the javascript fill in the pennies -->
                    </div><!-- pile -->
                </div><!-- pool -->
                <div class="decksize" id="spacer">&nbsp;</div>
            </div><!-- pool-column -->
        </div><!--tableau -->
                
        
        <div class="you" id="you">
            <div class="hand-box">
                <div class="hand-row" id="hand-row">
                    <div class="hand" id="your-hand">
                        {% for cc in your_hand %}
                        <div class="card">{{ cc }}</div>
                        {% endfor %}
                    </div><!-- hand -->
                    <div class="purse" id="purse">
                        <div class="cash" id="cash">{{ your_cash }}</div>
                    </div><!-- purse -->
                </div><!-- hand-row -->
                <div class="control-box" id="control-box">
                    <div class="control" id="refresh-button">Refresh</div>
                </div><!-- control-box -->
            </div><!-- hand-box -->
        
        </div><!-- you -->

        <div class="msg" id="msg">{{ msg }}</div>

        <form action="{% url 'nothanks:game' tag %}" id="actions-form" method="post">
        {% csrf_token %}
        <input type="hidden" id="token-field" name="token" value="{{ token }}">
        <input type="hidden" id="which-card" name="card" value="unset">
        <input type="hidden" id="wallet" name="wallet" value="unset">
        <input type="hidden" id="move-field" name="move" value="refresh">
        <input type="hidden" id="how-field" name="how" value="whole-page">
        </form>

    </div><!-- container -->
</div><!-- main -->

<pre id="json_exposed">
</pre>

<script>    
$(document).ready(function() {
    
    var game_json = '{{ json_state|safe }}';
    var game_state = JSON.parse(game_json);
    
    // struggling to suppress Chrome's insistence on caching intermediate state
    window.history.replaceState({ "token" : "{{ token }}" }, null, "/nothanks/{{ tag }}/");
    console.log("setting state->token to {{ token }}");
    
    window.onpopstate = function (event)
    {
        console.log("popstate received");
        event.stopImmediatePropagation();
        event.preventDefault();
        if ( event.state )
        {
            console.log("event state is non-null");
            
            if  ("token" in event.state)
            {
                console.log("token in in event.state");
                
                if (event.state["token"] != "nobody")
                {
                    console.log("token is not nobody");
                    $("#token-field").val(event.state["token"]);
                }
            }
        }
        
        ajax_submit(true);
    };
    
    function sync_to_game_state ( state )
    {
        $("#json_exposed").html(JSON.stringify(state));
        
        $("#game-status").html(state["status"]);
        
        $("#msg").html(state["msg"]);
        if ( state["msg"] == "" )
        {
            $("#msg").hide();
        }
        else
        {
            $("#msg").show();
        }
        
        if ( "players" in state )
        {
            var contents = [];
            for ( let ii = 0; ii < state["players"].length; ++ii )
            {
                contents.push('<div class="player');
                if ( state["players"][ii]["nickname"] == state["your_nickname"] )
                {
                    contents.push(' player-is-you');
                }
                contents.push('" id="player-' + ii + '">');
                contents.push('<div class="nickname">' + state["players"][ii]["nickname"] + "</div>");
                contents.push('<div class="status">' + state["players"][ii]["status"] + "</div>");
                contents.push('<div class="points">Points: ' + state["players"][ii]["points"] + "</div>");
                
                contents.push('<div class="hand">');
                
                let prev = -1;
                
                for ( let jj = 0; jj < state["players"][ii]["hand"].length; ++jj )
                {
                    let cc = state["players"][ii]["hand"][jj];
                    contents.push('<div class="card');
                    if ( cc == prev + 1 )
                    {
                        contents.push(' adjacent');
                    }
                    contents.push('">' + cc + '</div>');
                    prev = cc;
                }
                
                contents.push('</div></div>'); // hand, player
            }
            
            $("#players").html(contents.join(""));
        }
        
        if ( state["card"] == "0" )
        {
            $("#current_card").html("");
        }
        else
        {
            $("#current_card").html(state["card"]);
        }
        
        if ( state["pool"] > 0 )
        {
            let pennies = [];
            
            for ( let ii = 0; ii < state["pool"]; ++ii )
            {
                pennies.push('<div class="penny"></div>');
            }
            
            $("#pile").html(pennies.join(""));
        }
        else
        {
            $("#pile").html("");
        }
        
        if ( state["deck_size"] > 0 )
        {
            $("#decksize").html(state["deck_size"] + " remaining");
        }
        else
        {
            $("#decksize").html("&nbsp;");
        }
        
        if ( "your_nickname" in state )
        {   
            var contents = [];

            let prev = -1;
            
            if ( state["your_hand"].length )
            {
                for ( let ii = 0; ii < state["your_hand"].length; ++ii )
                {
                    let cc = state["your_hand"][ii];
                    contents.push('<div class="card');
                    if ( cc == prev + 1 )
                    {
                        contents.push(' adjacent');
                    }
                    contents.push('">' + cc + '</div>');
                    prev = cc;
                }
            
                $("#your-hand").html(contents.join(""));
                $("#your-hand").show();
            }
            else
            {
                $("#your-hand").hide();
            }
            
            if ( state["your_cash"] )
            {
                $("#purse").show();
                $("#cash").html(state["your_cash"]);
                $("#wallet").val(state["your_cash"]);
            }
            else
            {
                $("#purse").hide();
                $("#wallet").val("unset");
            }
            
            // these form fields are used to filter duplicate requests
            $("#which-card").val(state["card"]);
            
            
            // controls
            
            // main actions use game components as buttons
                        
            if (state["actions"].includes("take"))
            {
                $("#current_card").click( function () {
                        $("#move-field").val("take");
                        submit_move();
                });
                $("#current_card").css("cursor", "pointer");
            }
            else
            {
                $("#current_card").off("click");
                $("#current_card").css("cursor", "default");
            }
            
            if (state["actions"].includes("pay"))
            {
                $("#purse").click( function () {
                        $("#move-field").val("pay");
                        submit_move();
                });
                $("#purse").css("cursor", "pointer");
            }
            else
            {
                $("#purse").off("click");
                $("#purse").css("cursor", "default");
            }

            // remaining actions are all simple "buttons"            

            // always start control strip with just refresh, which should ensure
            // consistent ordering
            $("#refresh-button").nextAll().remove();
            
            if (state["actions"].includes("start"))
            {
                $("#control-box").append("<div class='control' id='start-button'>Start Game</div>");
                $("#start-button").click( function () {
                        $("#move-field").val("start");
                        submit_move();
                });
            }
                        
            if (state["actions"].includes("end_round"))
            {
                $("#control-box").append("<div class='control' id='end-round-button'>End Round</div>");
                $("#end-round-button").click( function () {
                        $("#move-field").val("end_round");
                        submit_move();
                });
            }

            if (state["actions"].includes("destroy"))
            {
                $("#control-box").append("<div class='control' id='destroy-button'>Destroy Game</div>");
                $("#destroy-button").click( function () {
                        $("#move-field").val("destroy");
                        submit_move();
                });
            }

        }
        else
        {
            $("#hand-row").hide();
        }
        
    }
    
    function submit_move ()
    {
        ajax_submit();
    }
    
    function hard_refresh ()
    {
        $("#move-field").val("refresh");
        document.querySelector("#how-field").value = "whole-page";
        document.querySelector("#actions-form").submit()
    }
    
    function soft_refresh ()
    {
        ajax_submit(true);
    }
    
    function ajax_submit(refresh=false)
    {
        if ( refresh )
        {
            $("#move-field").val("refresh");
        }
        success_func = refresh ? function (response) { sync_to_game_state(response) } : function (response) {};
        
        document.querySelector("#how-field").value = "json";
        
        $.ajax({ type: 'POST',
                 url: $("form").attr("action"),
                 data: $("form").serialize(),
                 success: success_func,
        });    
    }

    $("#refresh-button").click(soft_refresh);

    var es = new ReconnectingEventSource('/events/{{ tag }}/');

    es.addEventListener('message', function (e) {
        console.log(e.data);
        var dat = JSON.parse(e.data);
        if (dat["text"] == "index")
        {
            window.location.replace("/nothanks/");
        }
        else if (dat["text"] == "refresh")
        {
             ajax_submit(true);
        }
        else
        {
            console.log("unknown event: '" + e.data + "'");
        }
        
    }, false);

    es.addEventListener('stream-reset', function (e) { console.log(e.data); }, false);

    sync_to_game_state ( game_state );
});    
</script>

</body>
</html>

nothanks/templates/nothanks/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8"/>
    <link href="{% static 'join.css' %}" rel="stylesheet" type="text/css">
    <title>No Thanks</title>
</head>
<body>
<div class="container">
<h1>NO THANKS</h1>
    
{% if msg %}
<div class="msg">{{ msg }}</div>
{% endif %}

<div class="join-box">
<h2>Join a game</h2>
<form action="{% url 'nothanks:index' %}" method="post" id="join-form">
{% csrf_token %}
    <div class="join-chunk">
        <label>Game Name</label><br>
        <input id="game-name" type="text" size="16" required pattern="[A-Za-z0-9_]+" class="join-field" autofocus/>
    </div>
    
    <div class="join-chunk">
        <label>Player Name</label><br>
        <input id="nick" type="text" size="16" required pattern="[A-Za-z0-9_]+" name="nick" class="join-field"/>
    </div><!-- join-chunk -->

    <div class="join-chunk note">Allowed characters: letters, numbers, underscores</div>
    
    
    <div class="join-chunk">
        <label for="num_rounds">Rounds: </label>
        <input type="number" id="rounds-field" min="1" max="7" value="3" name="num_rounds" />
    </div><!-- join-chunk -->
    
    <div class="join-chunk">
        <input type="checkbox" name="house_rules" value="yes" />
        <label for="house_rules">House Rules</label>
    </div><!-- join-chunk -->

    <div class="join-chunk note">
        House rules end the move when you take a card.
        Game options are ignored when joining a game that already exists.
    </div>
    

    <div class="control" id="join">Join</div>
    <input type="hidden" name="move" value="join">
</form>
</div><!-- join-box -->

<script>
    document.querySelector('#nick').onkeyup = function(e)
    {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#join').click();
        }
    };

    document.querySelector('#join').onclick = function(e)
    {
        var gameName = document.querySelector('#game-name').value;
        document.querySelector('#join-form').action = '/nothanks/' + gameName + '/';
        if ( document.querySelector('#join-form').reportValidity() )
        {
            document.querySelector('#join-form').submit();
        }
    };
</script>
</div><!-- container -->
</body>
</html>